import type { INodeProps } from '@lightningjs/renderer';

export const defaultProps: Omit<INodeProps<any>, 'shader' | 'parent' | 'textureOptions'> = {
  alpha: 0,
  autosize: false,
  clipping: false,
  color: 0x00000000,
  colorBl: 0,
  colorBottom: 0,
  colorBr: 0,
  colorLeft: 0,
  colorRight: 0,
  colorTl: 0,
  colorTop: 0,
  colorTr: 0,
  height: 0,
  mount: 0,
  mountX: 0,
  mountY: 0,
  pivot: 0,
  pivotX: 0,
  pivotY: 0,
  rotation: 0,
  rtt: false,
  scale: 0,
  scaleX: 0,
  scaleY: 0,
  src: '',
  texture: null,
  // textureOptions: {} as TextureOptions,
  width: 0,
  x: 0,
  y: 0,
  zIndex: 0,
  zIndexLocked: 0,
};
